version: '3'
services:

  php:
    build:
      args:
        user: yossef
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    container_name: backend-php
    restart: unless-stopped
    volumes:
      - ./:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=sql"
      - "DB_USERNAME=sql"
      - "DB_PASSWORD=sql"
      - "DB_PORT=3306"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    depends_on:
      - mysql
      - redis
    networks:
      - service-network

  nginx:
    image: nginx:alpine
    container_name: web-server
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - php
    networks:
      - service-network

  mysql:
    image: mariadb:10.5.8
    container_name: backend-mysql
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=sql"
      - "MYSQL_DATABASE=sql"
      - "MYSQL_USER=sql"
      - "MYSQL_PASSWORD=sql"
    ports:
      - "3307:3306"
    networks:
      - service-network

  phpmyadmin:
    image: phpmyadmin
    container_name: backend-phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - service-network

  redis:
    image: redis:4.0-alpine
    container_name: backend-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - service-network

volumes:
  mysqldata:

networks:
  service-network:
    driver: bridge